version: '3.3'

services:
  market-management-db: 
    image: mysql:8.0
    container_name: mysql_container
    command: --innodb-use-native-aio=0 --ssl=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ms_market_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
